### ISSUE TITLE
TIME_SCALE

### ISSUE THREAD

**Issue by Zizzzzzzz** [82magnolia/n_imagenet#1]
Hello, it is a wonderful job! I have a question about the code.
What is the point of this line of code
`event[:, 2] /= TIME_SCALE`
Thanks!

**Comment by 82magnolia** [comment]
Hi! Sorry for the late reply. The timestamps in N-ImageNet is stored in micro-seconds. Therefore, for unit conversion to seconds, we divide the original event data by the TIME_SCALE.
