### ISSUE TITLE
some thing wrong when i run the code

### ISSUE THREAD

**Issue by Derekerrr** [82magnolia/n_imagenet#2]
![image](https://user-images.githubusercontent.com/73779648/229487017-7c96912b-5cec-47d7-b64b-75e5d7c9e0ae.png)
it happens when i run the code, i can not figure it out

**Comment by 82magnolia** [comment]
Hi, could you specify the command you used before obtaining the error message?

**Comment by Derekerrr** [comment]
Thank you for answering my questions。


the situation is:


i created the conda environment and downloaded source code as the github readme file tells on my windows laptop with nvidia 3060 GPU.





i also downloaded the mini-N_imagenet dataset(around 40 GB size)&nbsp; and changed the path in the train_list.txt and val_list.txt.
i thought everything was ok.
but when i run the code with the command below:&nbsp;
&nbsp; &nbsp; &nbsp;python main.py --config configs/imagenet/cnn_adam_acc_two_channel_big_kernel_random_idx_mini.ini


an error happpened:



below is the python console message：


slice_augment_width=0
slice_start=0
slice_end=30000
[Train]
optimizer=Adam
epochs=100
save_every=1
learning_rate=0.0003
momentum=0.9
weight_decay=1e-4
temperature=1
max_trajectory_speed=0.0
mahalanobis=0.0
noise_inject=True
[Debug]
debug=False
debug_input=True
inspect_channel=all
If config is correct, press y: &gt;? y
Initializing data container ImageNetContainer...
Initializing model container CNNContainer...
E:\conda\envs\e2t\lib\site-packages\torchvision\models\_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
&nbsp; f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
E:\conda\envs\e2t\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
&nbsp; warnings.warn(msg)
Using ResNet34 for training
Initializing trainer CNNTrainer...
Using Adam as optimizer
Number of GPUs: 1
Number of model parameters in model: 21351652
Model size of model: 81 MB
ResNet(
&nbsp; (conv1): Conv2d(2, 64, kernel_size=(14, 14), stride=(2, 2), padding=(3, 3), bias=False)
&nbsp; (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; (relu): ReLU(inplace=True)
&nbsp; (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
&nbsp; (layer1): Sequential(
&nbsp; &nbsp; (0): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (1): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (2): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; )
&nbsp; (layer2): Sequential(
&nbsp; &nbsp; (0): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (downsample): Sequential(
&nbsp; &nbsp; &nbsp; &nbsp; (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
&nbsp; &nbsp; &nbsp; &nbsp; (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (1): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (2): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (3): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; )
&nbsp; (layer3): Sequential(
&nbsp; &nbsp; (0): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (downsample): Sequential(
&nbsp; &nbsp; &nbsp; &nbsp; (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
&nbsp; &nbsp; &nbsp; &nbsp; (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (1): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (2): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (3): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (4): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (5): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; )
&nbsp; (layer4): Sequential(
&nbsp; &nbsp; (0): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (downsample): Sequential(
&nbsp; &nbsp; &nbsp; &nbsp; (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
&nbsp; &nbsp; &nbsp; &nbsp; (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (1): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; &nbsp; (2): BasicBlock(
&nbsp; &nbsp; &nbsp; (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; &nbsp; (relu): ReLU(inplace=True)
&nbsp; &nbsp; &nbsp; (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
&nbsp; &nbsp; &nbsp; (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
&nbsp; &nbsp; )
&nbsp; )
&nbsp; (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
&nbsp; (fc): Linear(in_features=512, out_features=100, bias=True)
)
This is 1-th epoch.
Traceback (most recent call last):
&nbsp; File "E:\conda\envs\e2t\lib\code.py", line 90, in runcode
&nbsp; &nbsp; exec(code, self.locals)
&nbsp; File "<input&gt;", line 1, in <module&gt;
&nbsp; File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
&nbsp; &nbsp; pydev_imports.execfile(filename, global_vars, local_vars)&nbsp; # execute the script
&nbsp; File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
&nbsp; &nbsp; exec(compile(contents+"\n", file, 'exec'), glob, loc)
&nbsp; File "E:\my_code\n_imagenet-main\n_imagenet-main\real_cnn_model\main.py", line 94, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "E:\my_code\n_imagenet-main\n_imagenet-main\real_cnn_model\main.py", line 90, in main
&nbsp; &nbsp; trainer.run()
&nbsp; File "E:\my_code\n_imagenet-main\n_imagenet-main\base\train\common_trainer.py", line 68, in run
&nbsp; &nbsp; self.run_epoch()
&nbsp; File "E:\my_code\n_imagenet-main\n_imagenet-main\base\train\common_trainer.py", line 87, in run_epoch
&nbsp; &nbsp; self.train_epoch()
&nbsp; File "E:\my_code\n_imagenet-main\n_imagenet-main\base\train\common_trainer.py", line 141, in train_epoch
&nbsp; &nbsp; for batch_idx, data_dict in enumerate(self.data_container.dataloader['train']):
&nbsp; File "E:\conda\envs\e2t\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
&nbsp; &nbsp; return self._get_iterator()
&nbsp; File "E:\conda\envs\e2t\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
&nbsp; &nbsp; return _MultiProcessingDataLoaderIter(self)
&nbsp; File "E:\conda\envs\e2t\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
&nbsp; &nbsp; w.start()
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\process.py", line 112, in start
&nbsp; &nbsp; self._popen = self._Popen(self)
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\context.py", line 223, in _Popen
&nbsp; &nbsp; return _default_context.get_context().Process._Popen(process_obj)
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\context.py", line 322, in _Popen
&nbsp; &nbsp; return Popen(process_obj)
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
&nbsp; &nbsp; reduction.dump(process_obj, to_child)
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\reduction.py", line 60, in dump
&nbsp; &nbsp; ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'base.utils.parse_utils.Config'&gt;: attribute lookup Config on base.utils.parse_utils failed
Traceback (most recent call last):
&nbsp; File "<string&gt;", line 1, in <module&gt;
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\spawn.py", line 105, in spawn_main
&nbsp; &nbsp; exitcode = _main(fd)
&nbsp; File "E:\conda\envs\e2t\lib\multiprocessing\spawn.py", line 115, in _main
&nbsp; &nbsp; self = reduction.pickle.load(from_parent)
EOFError: Ran out of input







吴汉超
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "82magnolia/n_imagenet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [82magnolia/n_imagenet] some thing wrong when i run the code (Issue #2)





 
Hi, could you specify the command you used before obtaining the error message?
