### ISSUE TITLE
timestep

### ISSUE THREAD

**Issue by Dazidingo** [82magnolia/n_imagenet#5]
Hello,
I found that after the event data format (x, y, t, p) is reshaped to (2, H, W), why is t missing, not (t, 2, H, W)

**Comment by 82magnolia** [comment]
Hi, would you specify the code fragment where you found the issue? Nonetheless, I feel you're asking why the event representations used in the codebase has shape (N, 2, H, W). Note this is how typical event representations look like: event at short timestamps are aggregated to form image-like representations.
