### ISSUE TITLE
Implementations of Other Event Representations

### ISSUE THREAD

**Issue by ldkong1205** [82magnolia/n_imagenet#7]
Hi @82magnolia, thanks for sharing this impressive work!

I am new to this area. I am learning different event representations as specified in your paper. I wonder whether it is possible to share the implementations for all representations mentioned in Table 4 and Table 6, such as MatrixLSTM, Event Spike Tensor, and HATS. Thanks!

**Comment by 82magnolia** [comment]
Hi! I apologize for the late reply. For MatrixLSTM and Event Spike Tensor, we used the publicly available code released by the authors:
- MatrixLSTM: https://github.com/marcocannici/matrixlstm
- Event Spike Tensor: https://github.com/uzh-rpg/rpg_event_representation_learning

For HATS, we referred to the following codebase: https://github.com/rfma23/HATS.

Hope this helped!
